/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EnchantsRouteImport } from './routes/enchants'
import { Route as MilestonesRouteImport } from './routes/milestones'
import { Route as FishIndexRouteImport } from './routes/fish.index'
import { Route as FishIdRouteImport } from './routes/fish.$id'
import { Route as HuntsIndexRouteImport } from './routes/hunts.index'
import { Route as HuntsIdRouteImport } from './routes/hunts.$id'
import { Route as ItemsIndexRouteImport } from './routes/items.index'
import { Route as ItemsIdRouteImport } from './routes/items.$id'
import { Route as RodsIdRouteImport } from './routes/rods.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnchantsRoute = EnchantsRouteImport.update({
  id: '/enchants',
  path: '/enchants',
  getParentRoute: () => rootRouteImport,
} as any)
const MilestonesRoute = MilestonesRouteImport.update({
  id: '/milestones',
  path: '/milestones',
  getParentRoute: () => rootRouteImport,
} as any)
const FishIndexRoute = FishIndexRouteImport.update({
  id: '/fish/',
  path: '/fish/',
  getParentRoute: () => rootRouteImport,
} as any)
const FishIdRoute = FishIdRouteImport.update({
  id: '/fish/$id',
  path: '/fish/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HuntsIndexRoute = HuntsIndexRouteImport.update({
  id: '/hunts/',
  path: '/hunts/',
  getParentRoute: () => rootRouteImport,
} as any)
const HuntsIdRoute = HuntsIdRouteImport.update({
  id: '/hunts/$id',
  path: '/hunts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsIndexRoute = ItemsIndexRouteImport.update({
  id: '/items/',
  path: '/items/',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsIdRoute = ItemsIdRouteImport.update({
  id: '/items/$id',
  path: '/items/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RodsIdRoute = RodsIdRouteImport.update({
  id: '/rods/$id',
  path: '/rods/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/enchants': typeof EnchantsRoute
  '/milestones': typeof MilestonesRoute
  '/fish/$id': typeof FishIdRoute
  '/hunts/$id': typeof HuntsIdRoute
  '/items/$id': typeof ItemsIdRoute
  '/rods/$id': typeof RodsIdRoute
  '/fish/': typeof FishIndexRoute
  '/hunts/': typeof HuntsIndexRoute
  '/items/': typeof ItemsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/enchants': typeof EnchantsRoute
  '/milestones': typeof MilestonesRoute
  '/fish/$id': typeof FishIdRoute
  '/hunts/$id': typeof HuntsIdRoute
  '/items/$id': typeof ItemsIdRoute
  '/rods/$id': typeof RodsIdRoute
  '/fish': typeof FishIndexRoute
  '/hunts': typeof HuntsIndexRoute
  '/items': typeof ItemsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/enchants': typeof EnchantsRoute
  '/milestones': typeof MilestonesRoute
  '/fish/$id': typeof FishIdRoute
  '/hunts/$id': typeof HuntsIdRoute
  '/items/$id': typeof ItemsIdRoute
  '/rods/$id': typeof RodsIdRoute
  '/fish/': typeof FishIndexRoute
  '/hunts/': typeof HuntsIndexRoute
  '/items/': typeof ItemsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/enchants'
    | '/milestones'
    | '/fish/$id'
    | '/hunts/$id'
    | '/items/$id'
    | '/rods/$id'
    | '/fish/'
    | '/hunts/'
    | '/items/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/enchants'
    | '/milestones'
    | '/fish/$id'
    | '/hunts/$id'
    | '/items/$id'
    | '/rods/$id'
    | '/fish'
    | '/hunts'
    | '/items'
  id:
    | '__root__'
    | '/'
    | '/enchants'
    | '/milestones'
    | '/fish/$id'
    | '/hunts/$id'
    | '/items/$id'
    | '/rods/$id'
    | '/fish/'
    | '/hunts/'
    | '/items/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EnchantsRoute: typeof EnchantsRoute
  MilestonesRoute: typeof MilestonesRoute
  FishIdRoute: typeof FishIdRoute
  HuntsIdRoute: typeof HuntsIdRoute
  ItemsIdRoute: typeof ItemsIdRoute
  RodsIdRoute: typeof RodsIdRoute
  FishIndexRoute: typeof FishIndexRoute
  HuntsIndexRoute: typeof HuntsIndexRoute
  ItemsIndexRoute: typeof ItemsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enchants': {
      id: '/enchants'
      path: '/enchants'
      fullPath: '/enchants'
      preLoaderRoute: typeof EnchantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/milestones': {
      id: '/milestones'
      path: '/milestones'
      fullPath: '/milestones'
      preLoaderRoute: typeof MilestonesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fish/': {
      id: '/fish/'
      path: '/fish'
      fullPath: '/fish/'
      preLoaderRoute: typeof FishIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fish/$id': {
      id: '/fish/$id'
      path: '/fish/$id'
      fullPath: '/fish/$id'
      preLoaderRoute: typeof FishIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hunts/': {
      id: '/hunts/'
      path: '/hunts'
      fullPath: '/hunts/'
      preLoaderRoute: typeof HuntsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hunts/$id': {
      id: '/hunts/$id'
      path: '/hunts/$id'
      fullPath: '/hunts/$id'
      preLoaderRoute: typeof HuntsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items/': {
      id: '/items/'
      path: '/items'
      fullPath: '/items/'
      preLoaderRoute: typeof ItemsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items/$id': {
      id: '/items/$id'
      path: '/items/$id'
      fullPath: '/items/$id'
      preLoaderRoute: typeof ItemsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rods/$id': {
      id: '/rods/$id'
      path: '/rods/$id'
      fullPath: '/rods/$id'
      preLoaderRoute: typeof RodsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EnchantsRoute: EnchantsRoute,
  MilestonesRoute: MilestonesRoute,
  FishIdRoute: FishIdRoute,
  HuntsIdRoute: HuntsIdRoute,
  ItemsIdRoute: ItemsIdRoute,
  RodsIdRoute: RodsIdRoute,
  FishIndexRoute: FishIndexRoute,
  HuntsIndexRoute: HuntsIndexRoute,
  ItemsIndexRoute: ItemsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
